# Generated by Django 4.2.8 on 2023-12-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='candidates',
            field=models.ManyToManyField(blank=True, through='customers.CustomerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vacancy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, through='customers.UserTask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisites',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.country'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='vacancies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vacancies'),
        ),
        migrations.AddField(
            model_name='customer',
            name='candidates',
            field=models.ManyToManyField(blank=True, through='customers.CustomerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='requisites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customers.requisites'),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='customeruser',
            unique_together={('customer', 'user', 'vacancies')},
        ),
    ]
