# Generated by Django 4.2.8 on 2023-12-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_responsible_alter_customer_candidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='responsible',
            new_name='manager',
        ),
    ]
